### ISSUE TITLE
Классы не компилируются

### ISSUE THREAD

**Issue by ghost** [Arrrlekino/GoIT#1]
Классы, которые залиты не компилируются. Это вызвано из-за неверной декларации классов, отсутствия нужных импортов и тд. Такое чувство, что код примеров, был сгенерирован при помощи сторонней программы, возможно UML to Java генератором.
Не могу оценить задание на данном этапе.

**Comment by Arrrlekino** [comment]
Шо вы говорите? Тем самым шо вы посоветовали (аргоумл) и сгенерировали код,
Естесственно! А про то шо классы надо декларировать да еще и "верно", с
"присутствием" импортов и т.д. " где я могла узнать? Может из вашил лекций?
А нет, там ничего такого не давали :(  Ну и шо мне теперь делать?

понедельник, 14 декабря 2015 г. пользователь Vlad Krava написал:

**Comment by ghost** [comment]
Ну делать так, чтоб оно работало... 
я за запрещал генерировать классы, но если уж вы пошли по данному пути, значит вы должны делать так, что б они были рабочими... у вас был и другой вариант, опираясь на знания полученные в первом задании решить второе... да конечно, оно немного усложнилось из-за того, что появились различные отношения между классами, но суть создания классов осталась прежней.
удачи!

**Comment by Arrrlekino** [comment]
Внезапно!
Я тут чисто случайно заметила в ДЗ к Модулю 3 :
"Написать классы на Java соответствующие UML диаграмме из задания к Модулю
2.
Создать проект с исходниками и загрузить его на GitHub. "  ?! - то есть в
задании к Модулю 2 классы писать вообще не надо было, а только UML
диаграмму? Кто ж мог догадаться шо "Создать классы" - это нарисовать УМЛ
графическую схему,,, А шо ж вы мне тогда про мои диаграммы ничего не
написали? Может они верные и это и есть выполненное ДЗ к Модулю 3 ?

15 декабря 2015 г., 11:22 пользователь Vlad Krava notifications@github.com
написал:

**Comment by ghost** [comment]
Вы верно заметили по поводу 3го задания... я начал говорить про классы и совсем забыл упомянуть ошибки в UML.
Там не все правильно,  есть ошибки связанные с логикой наследования, например, как файл может наследоваться от текстового файла... такие же ошибки по всему заданию.
так же я не увидел агрегации на диаграммах, только наследование.

**Comment by Arrrlekino** [comment]
У меня же В заданиях 1 и 2 на схемах линии, соединяющие прямоугольники,
линии с незаштрихованным ромбиком - это же " агрегация",  так и под кнопкой
АргоУмл написано и в инете статья про это, могу ссылку кинуть. А в задании
3 ромбики заштрихованы - " композиция" Это неправильная статья? Где
тогда правильная?  Вообще я не пойму суть нашей переписки. Это у меня
защита проекта или шо? Или вы ставите своей целью доказать шо я не знаю
Яву, а вы таки ее знаете? Так с этим я не спорю, это прописано в условиях
подписанного нами договора. Но там же есть пункт о том шо вы меня обучаете.
А обучение предполагает не только и не столько рассказы о том чего я не
знаю что неправильно, а разъяснение - Как надо правильно! Я не хочу на вас
свалить все мое обучение, но мне ж обещали шо кроме лекций еще и на все
вопросы Ментор будет давать пояснения, а как же мне без пояснений в срок
уложиться, если в лекциях материала к заданию не было! . Вы как мне кажется
свою роль поняли совсем иначе - как проверяющего задания, причем критерии
оценки и сроки тоже весьма приблизительные. Как то неконструктивно и
непродуктивно получается. Вроде и времени вы на меня много тратите и
отвечаете шо то, а новых познаний у меня сегодня не добавилось. Может стоит
уточнить у организаторов какие-то рамки полномочий? Я вовсе не хочу
понапрасну вас беспокоить.

вторник, 15 декабря 2015 г. пользователь Vlad Krava написал:

**Comment by Arrrlekino** [comment]
Это графические схемы Задание к Модулю 2

14 декабря 2015 г., 23:36 пользователь Vlad Krava notifications@github.com
написал:

**Comment by ghost** [comment]
тогда переименуйте классы в задание 3
